# Nome do aplicativo no Fly.io
app = "todolist-springboot"


# Configurações de máquinas virtuais
[machine]
# Quantidade de vCPUs que a máquina virtual terá
cpu = "shared-1x"
# Quantidade de memória para a máquina
memory = 512 # 512 MB

[build]
image = "registry.fly.io/todolist-springboot:deployment-fb728d3950d975d0821fe25b744ba83e"

[env]
SPRING_PROFILES_ACTIVE = "prod"
JAVA_OPTS = "-Xmx512m -Xms256m"

[[services]]
internal_port = 8080
protocol = "tcp"

# Porta externa acessível
[services.concurrency]
hard_limit = 10
soft_limit = 5

[services.http]
# Configuração de rotas para o serviço
[[services.http.routes]]
handler = "static"
url = "/*"
