# Nome do aplicativo no Fly.io
app = "todolist-springboot"

# Configurações de máquinas virtuais
[machine]
cpu = "shared-1x"
memory = 512 # 512 MB

[build]
image = "registry.fly.io/todolist-springboot:deployment-fb728d3950d975d0821fe25b744ba83e"

[env]
SPRING_PROFILES_ACTIVE = "prod"
JAVA_OPTS = "-Xmx512m -Xms256m"

[[services]]
internal_port = 8080
protocol = "tcp"

# Configuração de concorrência (limite de conexões)
[services.concurrency]
hard_limit = 10
soft_limit = 5

# Exposição de porta para tráfego HTTP
[[services.ports]]
handlers = ["http"]
port = 80

[[services.http.routes]]
handler = "static"
url = "/*"
