# Nome do aplicativo no Fly.io
app = "todolist-springboot"

# Configuração da máquina virtual
[machine]
cpu = "shared-1x"
memory = 512 # 512 MB RAM

# Configuração para otimizar escalabilidade
[mount]
source = "todolist_data"
destination = "/app/data"
auto_stop_machines = true
auto_start_machines = true

# Variáveis de ambiente do Spring Boot
[env]
SPRING_PROFILES_ACTIVE = "prod"
JAVA_OPTS = "-Xmx512m -Xms256m"

# Configuração dos serviços
[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 10
soft_limit = 5

[[services.ports]]
handlers = ["http"]
port = 80
